version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - GOOGLE_API_KEY="${GOOGLE_API_KEY}"
